require "test_helper"

class SearchParamsTest < ActiveSupport::TestCase
  test "normalizes permitted values into an immutable search value object" do
    params = SearchParams.for(
      :evaluation_target,
      "keyword" => "Ruby",
      "per_page" => "25"
    ).assert_known!

    assert params.frozen?
    assert params.values.frozen?
    assert_equal "Ruby", params.keyword
    assert_equal "25", params[:per_page]
    assert_equal({ keyword: "Ruby", per_page: "25" }, params.to_h)
  end

  test "rejects unknown search parameters instead of silently accepting them" do
    params = SearchParams.for(:evaluation_target, keyword: "Ruby", unsafe_order: "name desc")

    error = assert_raises(SearchParams::UnknownKeyError) do
      params.assert_known!
    end

    assert_includes error.message, "unsafe_order"
  end

  test "only allowlisted accessors are generated by metaprogramming" do
    params = SearchParams.for(:review_queue, comment_keyword: "migration", statuses: %w[submitted returned]).assert_known!

    assert_equal "migration", params.comment_keyword
    assert_equal %w[submitted returned], params.statuses
    assert_not_respond_to params, :unsafe_order
  end

  test "search classes reject unknown parameters at query boundary" do
    error = assert_raises(SearchParams::UnknownKeyError) do
      Search::EvaluationTargetSearch.new(EvaluationTarget.all, keyword: "Ruby", unsafe_order: "name desc").relation
    end

    assert_includes error.message, "unsafe_order"
  end

  test "search allowlist constants are frozen" do
    assert SearchParams::CONTEXTS.frozen?
    assert SearchParams::CONTEXTS.fetch(:evaluation_target).frozen?
    assert SearchParams::METHOD_NAMES.frozen?
  end
end
